osx_image: xcode11.4.1
language: swift
cache: cocoapods
podfile: Alzura-CodeTask/Podfile
os: osx
xcode_project: Alzura-CodeTask.xcodeproj
xcode_scheme: Alzura-CodeTask
xcode_destination: platform=iOS Simulator,OS=13.0,name=iPhone 11 Pro Max

before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod repo update
- pod install 
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Alzura-CodeTask.xcworkspace -scheme Alzura-CodeTask -sdk iphonesimulator -destination 'name=iPhone 11 Pro Max' ONLY_ACTIVE_ARCH=NO | xcpretty